[package]
org = "ayesha"
name = "tavily"
version = "@toml.version@"
distribution = "2201.13.0"
keywords = ["ai", "search", "web-search", "research"]
license = ["Apache-2.0"]
icon = "icon.png"
readme = "Package.md"
repository="https://github.com/ayeshLK/module-tavily"

[build-options]
observabilityIncluded = true
