// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, Ayesh Almeida.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied. See the License for the specific
// language governing permissions and limitations under the License.

import ballerina/data.jsondata;
import ballerina/http;

# Tavily is a search engine built for AI agents and LLMs. This OpenAPI
# specification covers the Tavily REST API, including web search, content
# extraction, site crawling, site mapping, deep research, and usage tracking.
# 
# ## Authentication
# All endpoints require a Tavily API key supplied as a bearer token:
# 
# ```
# Authorization: Bearer tvly-YOUR_API_KEY
# ```
# 
# Get a free API key from the [Tavily platform](https://app.tavily.com).
# 
# ## Optional tracking headers
# Most endpoints accept optional headers to organize and analyze requests:
# `X-Project-ID`, `X-Session-Id`, and `X-Human-Id`.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.tavily.com") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Search the web
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful search 
    resource isolated function post search(SearchRequest payload, SearchHeaders headers = {}) returns SearchResponse|error {
        string resourcePath = string `/search`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Extract content from URLs
    #
    # + headers - Headers to be sent with the request 
    # + return - Extraction results 
    resource isolated function post extract(ExtractRequest payload, ExtractHeaders headers = {}) returns ExtractResponse|error {
        string resourcePath = string `/extract`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Crawl a website
    #
    # + headers - Headers to be sent with the request 
    # + return - Crawl results 
    resource isolated function post crawl(CrawlRequest payload, CrawlHeaders headers = {}) returns CrawlResponse|error {
        string resourcePath = string `/crawl`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Map a website
    #
    # + headers - Headers to be sent with the request 
    # + return - Map results 
    resource isolated function post 'map(MapRequest payload, MapHeaders headers = {}) returns MapResponse|error {
        string resourcePath = string `/map`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Create a research task
    #
    # + headers - Headers to be sent with the request 
    # + return - Research task created 
    resource isolated function post research(ResearchRequest payload, CreateResearchHeaders headers = {}) returns ResearchTaskCreated|error {
        string resourcePath = string `/research`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get research task status and results
    #
    # + request_id - The unique identifier of the research task.
    # + headers - Headers to be sent with the request 
    # + return - Task completed or failed 
    resource isolated function get research/[string request_id](map<string|string[]> headers = {}) returns ResearchTaskCompleted|ResearchTaskFailed|ResearchTaskPending|error {
        string resourcePath = string `/research/${getEncodedUri(request_id)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get usage information
    #
    # + headers - Headers to be sent with the request 
    # + return - Usage information 
    resource isolated function get usage(GetUsageHeaders headers = {}) returns UsageResponse|error {
        string resourcePath = string `/usage`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }
}
