// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, Ayesh Almeida.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied. See the License for the specific
// language governing permissions and limitations under the License.

import ballerina/constraint;
import ballerina/http;

public type SearchRequest record {
    # The search query to execute.
    string query;
    # Controls the trade-off between latency and relevance. `advanced`
    # costs 2 credits; `basic`, `fast`, and `ultra-fast` cost 1 credit.
    "basic"|"advanced"|"fast"|"ultra-fast" search_depth = "basic";
    # Maximum number of relevant content chunks returned per source. Available only when `search_depth` is `advanced`.
    @constraint:Int {minValue: 1, maxValue: 3}
    int chunks_per_source = 3;
    # Maximum number of search results to return.
    @constraint:Int {minValue: 0, maxValue: 20}
    int max_results = 5;
    # The category of the search.
    "general"|"news" topic = "general";
    # Filter results by a relative time range from the current date.
    "day"|"week"|"month"|"year"|"d"|"w"|"m"|"y"? time_range?;
    # Return results published after this date (YYYY-MM-DD).
    string? start_date?;
    # Return results published before this date (YYYY-MM-DD).
    string? end_date?;
    # Include an LLM-generated answer. `true`/`basic` returns a quick answer; `advanced` returns a more detailed answer.
    boolean|"basic"|"advanced" include_answer = false;
    # Include the cleaned page content for each result. `true`/`markdown` returns markdown; `text` returns plain text.
    boolean|"markdown"|"text" include_raw_content = false;
    # Include a list of query-related images in the response.
    boolean include_images = false;
    # Add descriptive text for each image. Requires `include_images: true`.
    boolean include_image_descriptions = false;
    # Include the favicon URL for each result.
    boolean include_favicon = false;
    # A list of domains to specifically include in the results.
    @constraint:Array {maxLength: 300}
    string[] include_domains = [];
    # A list of domains to specifically exclude from the results.
    @constraint:Array {maxLength: 150}
    string[] exclude_domains = [];
    # Boost results from a specific country. Only available with the `general` topic.
    string? country?;
    # Automatically configure search parameters based on the query intent. Costs 2 credits.
    boolean auto_parameters = false;
    # Return only results matching exact quoted phrases in the query.
    boolean exact_match = false;
    # Include credit usage information in the response.
    boolean include_usage = false;
    # Filter out adult or unsafe content. Enterprise only; not available with `fast` or `ultra-fast` search depth.
    boolean safe_search = false;
};

# Represents the Headers record for the operation: map
public type MapHeaders record {
    # Optional session identifier for grouping related requests in analytics.
    string X\-Session\-Id?;
    # Optional identifier for the end user driving the request.
    string X\-Human\-Id?;
    # Optional project ID to scope the request to a specific project.
    string X\-Project\-ID?;
};

public type MapResponse record {
    # The mapped starting URL.
    string base_url?;
    # A list of URLs that were discovered during mapping.
    string[] results?;
    # Time in seconds it took to complete the request.
    float response_time?;
    # Credit usage details, included when `include_usage` is true.
    Usage usage?;
    # A unique request identifier you can share with customer support.
    string request_id?;
};

public type ResearchTaskFailed record {
    # The task identifier.
    string request_id?;
    # The task status.
    "failed" status?;
    # Seconds elapsed.
    int response_time?;
};

public type CrawlResponse record {
    # The base URL that was crawled.
    string base_url?;
    # A list of extracted content from the crawled URLs.
    CrawlResult[] results?;
    # Time in seconds it took to complete the request.
    float response_time?;
    # Credit usage details, included when `include_usage` is true.
    Usage usage?;
    # A unique request identifier you can share with customer support.
    string request_id?;
};

public type KeyUsage record {
    # Total credits used by this API key.
    int usage?;
    # The credit limit for this key, or null if unlimited.
    int? 'limit?;
    # Credits used by search requests.
    int search_usage?;
    # Credits used by extract requests.
    int extract_usage?;
    # Credits used by crawl requests.
    int crawl_usage?;
    # Credits used by map requests.
    int map_usage?;
    # Credits used by research requests.
    int research_usage?;
};

public type ExtractRequest record {
    # A single URL or a list of URLs (max 20) to extract content from.
    string|string[] urls;
    # User intent used to rerank extracted content chunks by relevance.
    string query?;
    # Maximum relevant chunks per source. Only available when `query` is set.
    @constraint:Int {minValue: 1, maxValue: 5}
    int chunks_per_source = 3;
    # Extraction level. `advanced` retrieves more data, including tables and embedded content.
    "basic"|"advanced" extract_depth = "basic";
    # Include a list of extracted image URLs in the response.
    boolean include_images = false;
    # Include the favicon URL for each result.
    boolean include_favicon = false;
    # The format of the extracted content.
    "markdown"|"text" format = "markdown";
    # Maximum time in seconds to wait for extraction. Defaults to 10s for `basic` and 30s for `advanced`.
    @constraint:Float {minValue: 1, maxValue: 60}
    float timeout?;
    # Include credit usage information in the response.
    boolean include_usage = false;
};

public type ResearchTaskCompleted record {
    # The task identifier.
    string request_id?;
    # Timestamp when the task was created (ISO 8601).
    string created_at?;
    # The task status.
    "completed" status?;
    # The research report content. A string, or a structured object when `output_schema` was provided.
    string|record {} content?;
    # The list of sources used in the research.
    ResearchSource[] sources?;
    # Seconds to complete the request.
    int response_time?;
};

public type ResearchTaskCreated record {
    # A unique identifier for the research task.
    string request_id?;
    # Timestamp when the research task was created (ISO 8601).
    string created_at?;
    # The current status of the task.
    string status?;
    # The research question submitted.
    string input?;
    # The model used by the research agent.
    string model?;
    # Processing time in seconds.
    float response_time?;
};

public type ResearchFile record {
    # The filename, including its extension.
    string name;
    # The base64-encoded file contents.
    string data;
    # The encoding type of the file data.
    string 'type = "base64";
};

public type ResearchSource record {
    # Title or name of the source.
    string title?;
    # URL of the source.
    string url?;
    # URL to the source's favicon.
    string favicon?;
};

# Represents the Headers record for the operation: extract
public type ExtractHeaders record {
    # Optional session identifier for grouping related requests in analytics.
    string X\-Session\-Id?;
    # Optional identifier for the end user driving the request.
    string X\-Human\-Id?;
    # Optional project ID to scope the request to a specific project.
    string X\-Project\-ID?;
};

public type ResearchRequest record {
    # The research task or question to investigate.
    string input;
    # Research agent model. `mini` is targeted and efficient; `pro` is comprehensive; `auto` selects automatically.
    "mini"|"pro"|"auto" model = "auto";
    # Whether to stream the research results as Server-Sent Events.
    boolean 'stream = false;
    # JSON Schema defining the structure of the output. Requires a `properties` field and an optional `required` field.
    record {}? output_schema?;
    # The citation style used in the report.
    "numbered"|"mla"|"apa"|"chicago" citation_format = "numbered";
    # Soft preference for sources. The agent prioritizes but is not limited to these domains.
    @constraint:Array {maxLength: 20}
    string[] include_domains = [];
    # Hard blocklist of domains and subdomains to avoid.
    @constraint:Array {maxLength: 20}
    string[] exclude_domains = [];
    # Target size of the response.
    "short"|"standard"|"long" output_length = "standard";
    # Up to 5 files (.txt, .md, .json) to include as context. Max 80,000 words per file and 80,000 words combined.
    @constraint:Array {maxLength: 5}
    ResearchFile[] files?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type AccountUsage record {
    # The account's current plan.
    string current_plan?;
    # Credits used against the plan allowance.
    int plan_usage?;
    # The plan credit limit.
    int plan_limit?;
    # Credits used under pay-as-you-go.
    int paygo_usage?;
    # The pay-as-you-go credit limit.
    int paygo_limit?;
    # Account-wide credits used by search requests.
    int search_usage?;
    # Account-wide credits used by extract requests.
    int extract_usage?;
    # Account-wide credits used by crawl requests.
    int crawl_usage?;
    # Account-wide credits used by map requests.
    int map_usage?;
    # Account-wide credits used by research requests.
    int research_usage?;
};

# Represents the Headers record for the operation: search
public type SearchHeaders record {
    # Optional session identifier for grouping related requests in analytics.
    string X\-Session\-Id?;
    # Optional identifier for the end user driving the request.
    string X\-Human\-Id?;
    # Optional project ID to scope the request to a specific project.
    string X\-Project\-ID?;
};

# Credit usage details, included when `include_usage` is true.
public type Usage record {
    # The number of credits consumed by the request.
    int credits?;
};

public type MapRequest record {
    # The root URL to begin the mapping.
    string url;
    # Natural language guidance for the crawler. Increases cost to 2 credits per 10 successful pages.
    string? instructions?;
    # Max depth of the mapping.
    @constraint:Int {minValue: 1, maxValue: 5}
    int max_depth = 1;
    # Max number of links to follow per level of the tree.
    @constraint:Int {minValue: 1, maxValue: 500}
    int max_breadth = 20;
    # Total number of links the crawler will process before stopping.
    @constraint:Int {minValue: 1}
    int 'limit = 50;
    # Regex patterns to select only URLs with specific path patterns.
    string[]? select_paths?;
    # Regex patterns to restrict mapping to specific domains or subdomains.
    string[]? select_domains?;
    # Regex patterns to exclude URLs with specific path patterns.
    string[]? exclude_paths?;
    # Regex patterns to exclude specific domains from mapping.
    string[]? exclude_domains?;
    # Whether to include external domain links in the results.
    boolean allow_external = true;
    # Maximum time in seconds to wait.
    @constraint:Float {minValue: 10, maxValue: 150}
    float timeout = 150;
    # Whether to include credit usage information in the response.
    boolean include_usage = false;
};

# Represents the Headers record for the operation: crawl
public type CrawlHeaders record {
    # Optional session identifier for grouping related requests in analytics.
    string X\-Session\-Id?;
    # Optional identifier for the end user driving the request.
    string X\-Human\-Id?;
    # Optional project ID to scope the request to a specific project.
    string X\-Project\-ID?;
};

# Represents the Headers record for the operation: createResearch
public type CreateResearchHeaders record {
    # Optional session identifier for grouping related requests in analytics.
    string X\-Session\-Id?;
    # Optional identifier for the end user driving the request.
    string X\-Human\-Id?;
    # Optional project ID to scope the request to a specific project.
    string X\-Project\-ID?;
};

public type SearchResult record {
    # The title of the result.
    string title?;
    # The URL of the result.
    string url?;
    # A short description of the result relevant to the query.
    string content?;
    # The relevance score of the result.
    float score?;
    # The cleaned page content, if `include_raw_content` was requested.
    string? raw_content?;
    # The favicon URL, if `include_favicon` was requested.
    string favicon?;
    # Images from this result, if `include_images` was requested.
    string[] images?;
};

public type ResearchTaskPending record {
    # The task identifier.
    string request_id?;
    # The current status of the task.
    "pending"|"in_progress" status?;
    # Seconds elapsed.
    int response_time?;
};

public type FailedResult record {
    # The URL that failed.
    string url?;
    # A description explaining the failure.
    string 'error?;
};

public type ExtractResult record {
    # The source URL.
    string url?;
    # The full extracted page content. When `query` is provided, contains the top-ranked chunks joined by `[...]`.
    string raw_content?;
    # Extracted image URLs, if `include_images` was requested.
    string[] images?;
    # The favicon URL, if `include_favicon` was requested.
    string favicon?;
};

public type SearchResponse record {
    # The executed search query.
    string query?;
    # The LLM-generated answer, if `include_answer` was requested.
    string answer?;
    # Query-related images, if `include_images` was requested.
    SearchImage[] images?;
    # Ranked search results.
    SearchResult[] results?;
    # The parameters selected automatically, if `auto_parameters` was enabled.
    record {} auto_parameters?;
    # Time in seconds it took to complete the request.
    float response_time?;
    # Credit usage details, included when `include_usage` is true.
    Usage usage?;
    # A unique request identifier you can share with customer support.
    string request_id?;
};

public type UsageResponse record {
    KeyUsage 'key?;
    AccountUsage account?;
};

public type ExtractResponse record {
    # Extracted content from the provided URLs.
    ExtractResult[] results?;
    # URLs that could not be processed.
    FailedResult[] failed_results?;
    # Time in seconds it took to complete the request.
    float response_time?;
    # Credit usage details, included when `include_usage` is true.
    Usage usage?;
    # A unique request identifier you can share with customer support.
    string request_id?;
};

public type CrawlRequest record {
    # The root URL to begin the crawl.
    string url;
    # Natural language instructions for the crawler. Increases cost to 2 credits per 10 successful pages.
    string? instructions?;
    # Maximum relevant chunks returned per source. Only available with `instructions`.
    @constraint:Int {minValue: 1, maxValue: 5}
    int chunks_per_source = 3;
    # Max depth of the crawl — how far from the base URL the crawler can explore.
    @constraint:Int {minValue: 1, maxValue: 5}
    int max_depth = 1;
    # Max number of links to follow per level of the tree.
    @constraint:Int {minValue: 1, maxValue: 500}
    int max_breadth = 20;
    # Total number of links the crawler will process before stopping.
    @constraint:Int {minValue: 1}
    int 'limit = 50;
    # Regex patterns to select only URLs with specific path patterns.
    string[]? select_paths?;
    # Regex patterns to restrict crawling to specific domains or subdomains.
    string[]? select_domains?;
    # Regex patterns to exclude URLs with specific path patterns.
    string[]? exclude_paths?;
    # Regex patterns to exclude specific domains from crawling.
    string[]? exclude_domains?;
    # Whether to include external domain links in the final results.
    boolean allow_external = true;
    # Whether to include images in the crawl results.
    boolean include_images = false;
    # Extraction quality level. `basic` costs 1 credit per 5 extractions; `advanced` costs 2 credits per 5.
    "basic"|"advanced" extract_depth = "basic";
    # Content format of extracted pages. `text` may increase latency.
    "markdown"|"text" format = "markdown";
    # Whether to include the favicon URL for each result.
    boolean include_favicon = false;
    # Maximum time in seconds before timeout.
    @constraint:Number {minValue: 10, maxValue: 150}
    decimal timeout = 150;
    # Whether to include credit usage information in the response.
    boolean include_usage = false;
};

public type CrawlResult record {
    # The URL that was crawled.
    string url?;
    # The full content extracted from the page. When `instructions` are provided, contains the top-ranked chunks joined by `[...]`.
    string raw_content?;
    # The favicon URL, if `include_favicon` was requested.
    string favicon?;
};

# Represents the Headers record for the operation: getUsage
public type GetUsageHeaders record {
    # Optional project ID to scope the request to a specific project.
    string X\-Project\-ID?;
};

public type SearchImage record {
    # The image URL.
    string url?;
    # Descriptive text, if `include_image_descriptions` was requested.
    string description?;
};
